name: "End-to-End test"

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: End-to-end test target
        uses: ./test/

  build-e2e-pyenv:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: pyenv test
        uses: ./test/e2e/pyenv