name: Upload Release Asset

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*.*.*' # Push events to matching v*, i.e. v1.0, v20.15.10

#on: [push]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Prepare
        run: |
          echo 'deb http://download.opensuse.org/repositories/home:/nsekiguchi/xUbuntu_22.04/ /' | \
            sudo tee /etc/apt/sources.list.d/home:nsekiguchi.list
          curl -fsSL https://download.opensuse.org/repositories/home:nsekiguchi/xUbuntu_22.04/Release.key | \
            gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/home_nsekiguchi.gpg > /dev/null
          sudo apt update
          sudo apt install arsh
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Build Release Asset
        run: |
          ./scripts/build_all.ds
          ls ./
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: 'shtx*'
