name: Upload Release Asset

#on:
#  push:
#    # Sequence of patterns matched against refs/tags
#    tags:
#      - 'v*.*.*' # Push events to matching v*, i.e. v1.0, v20.15.10

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: prepare
        run: |
          sudo apt update
          sudo apt install language-pack-ja ninja-build
          git clone https://github.com/sekiguchi-nagisa/ydsh.git
          mkdir -p ./ydsh/build
          cd ydsh && cd build && cmake .. -G Ninja && cmake --build . && sudo cmake --build . -- install
          ydsh -e shctl info
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Build Release Asset
        run: |
          ./scripts/build_all.ds
          ls ./